### ISSUE TITLE
Release 3.2.6 broken with NextCloud 19: Interface 'OCP\AppFramework\Bootstrap\IBootstrap' not found in w2g2/lib/AppInfo/Application.php

### ISSUE THREAD

**Issue by madmath03** [newroco/W2G2#66]
### Steps to reproduce
1. Install NextCloud 19.0.12.0
2. Install w2g2 from admin screens or CLI: `occ app:install w2g2` or update to latest 3.2.6 if already installed `occ app:update w2g2`

### Expected behaviour
Install should work or at least not break NextCloud.

### Actual behaviour
* Impossible to access NextCloud 19 from the browser (Internal server error) after an update
* Install of w2g2 3.2.6 fails

### Server configuration

**Operating system:** Official NextCloud Docker image, version 19, apache variant

**Web server:** Apache

**Database:** postgres:10-alpine (Docker)

**PHP version:** 

**Nextcloud version:** 19.0.12.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** DockerHub

**List of activated apps:**

After disabling w2g2 with `occ app:disable w2g2`:

<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - bookmarks: 3.4.9
  - calendar: 2.0.5
  - checksum: 0.4.5
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.5.1
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.2.7
  - drawio: 1.0.0
  - event_update_notification: 1.0.2
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_mindmap: 0.0.24
  - files_pdfviewer: 1.8.0
  - files_readmemd: 1.2.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - forms: 2.2.4
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.3
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 6.4.2
  - ownpad: 0.6.16
  - password_policy: 1.9.1
  - passwords: 2020.12.4
  - photos: 1.1.0
  - piwik: 0.8.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quota_warning: 1.8.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.10
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.0.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.1
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - maps
  - polls
  - w2g2
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "19.0.12.0",
        "overwrite.cli.url": "cloud.example.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** None

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+-------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                   |
+-------------------------------+-------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                     |
| homeFolderNamingRule          |                                                                                                       |
| lastJpegPhotoLookup           | 0                                                                                                     |
| ldapAgentName                 | cn=admin,dc=ldap,dc=example,dc=com                                                                   |
| ldapAgentPassword             | ***                                                                                                   |
| ldapAttributesForGroupSearch  |                                                                                                       |
| ldapAttributesForUserSearch   |                                                                                                       |
| ldapBackupHost                |                                                                                                       |
| ldapBackupPort                |                                                                                                       |
| ldapBase                      | dc=ldap,dc=example,dc=com                                                                            |
| ldapBaseGroups                | ou=Groups,dc=ldap,dc=example,dc=com                                                                  |
| ldapBaseUsers                 | ou=People,dc=ldap,dc=example,dc=com                                                                  |
| ldapCacheTTL                  | 600                                                                                                   |
| ldapConfigurationActive       | 1                                                                                                     |
| ldapDefaultPPolicyDN          |                                                                                                       |
| ldapDynamicGroupMemberURL     |                                                                                                       |
| ldapEmailAttribute            | mail                                                                                                  |
| ldapExperiencedAdmin          | 0                                                                                                     |
| ldapExpertUUIDGroupAttr       |                                                                                                       |
| ldapExpertUUIDUserAttr        |                                                                                                       |
| ldapExpertUsernameAttr        | uid                                                                                                   |
| ldapExtStorageHomeAttribute   |                                                                                                       |
| ldapGidNumber                 | gidNumber                                                                                             |
| ldapGroupDisplayName          | cn                                                                                                    |
| ldapGroupFilter               | (&(|(objectclass=groupOfNames)))                                                                      |
| ldapGroupFilterGroups         |                                                                                                       |
| ldapGroupFilterMode           | 0                                                                                                     |
| ldapGroupFilterObjectclass    | groupOfNames                                                                                          |
| ldapGroupMemberAssocAttr      | member                                                                                                |
| ldapHost                      | ldaps://ldap.example.com                                                                             |
| ldapIgnoreNamingRules         |                                                                                                       |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)(entryUUID=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                       |
| ldapLoginFilterEmail          | 1                                                                                                     |
| ldapLoginFilterMode           | 1                                                                                                     |
| ldapLoginFilterUsername       | 1                                                                                                     |
| ldapMatchingRuleInChainState  | unknown                                                                                               |
| ldapNestedGroups              | 0                                                                                                     |
| ldapOverrideMainServer        |                                                                                                       |
| ldapPagingSize                | 500                                                                                                   |
| ldapPort                      | 636                                                                                                   |
| ldapQuotaAttribute            |                                                                                                       |
| ldapQuotaDefault              |                                                                                                       |
| ldapTLS                       | 0                                                                                                     |
| ldapUserAvatarRule            | default                                                                                               |
| ldapUserDisplayName           | displayName                                                                                           |
| ldapUserDisplayName2          |                                                                                                       |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                                                                        |
| ldapUserFilterGroups          |                                                                                                       |
| ldapUserFilterMode            | 0                                                                                                     |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                         |
| ldapUuidGroupAttribute        | auto                                                                                                  |
| ldapUuidUserAttribute         | auto                                                                                                  |
| turnOffCertCheck              | 0                                                                                                     |
| turnOnPasswordChange          | 1                                                                                                     |
| useMemberOfToDetectMembership | 1                                                                                                     |
+-------------------------------+-------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:** NA

**Operating system:** NA

#### NextCloud CLI log

<details>
<summary>OCC install log</summary>

```
An unhandled exception has been thrown:
Error: Interface 'OCP\AppFramework\Bootstrap\IBootstrap' not found in var/www/html/custom_apps/w2g2/lib/AppInfo/Application.php:34
Stack trace:
#0 /var/www/html/lib/composer/composer/ClassLoader.php(444): include()
#1 /var/www/html/lib/composer/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/c...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('OCA\\w2g2\\AppInf...')
#3 [internal function]: spl_autoload_call('OCA\\w2g2\\AppInf...')
#4 /var/www/html/lib/private/ServerContainer.php(105): class_exists('OCA\\w2g2\\AppInf...')
#5 /var/www/html/lib/private/ServerContainer.php(132): OC\ServerContainer->getAppContainer('w2g2', 'w2g2')
#6 /var/www/html/lib/private/Repair.php(118): OC\ServerContainer->query('OCA\\w2g2\\Migrat...')
#7 /var/www/html/lib/private/legacy/OC_App.php(969): OC\Repair->addStep('OCA\\w2g2\\Migrat...')
#8 /var/www/html/lib/private/Installer.php(145): OC_App::executeRepairSteps('w2g2', Array)
#9 /var/www/html/core/Command/App/Install.php(66): OC\Installer->installApp('w2g2')
#10 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\
Output\ConsoleOutput))
#11 /var/www/html/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\C
onsole\Output\ConsoleOutput))
#12 /var/www/html/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Install), Object(Symfony\Component\Console\Inp
ut\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Cons
ole\Output\ConsoleOutput))
#14 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Out
put\ConsoleOutput))
#15 /var/www/html/console.php(100): OC\Console\Application->run()
#16 /var/www/html/occ(11): require_once('/var/www/html/c...')
#17 {main}
```
</details>

#### Web server error log

NA

#### Nextcloud log (data/nextcloud.log)

<details>
<summary>Server log</summary>

```

    {
        "reqId": "t8EI028sUxxIq5AMr74Q",
        "level": 3,
        "time": "2021-06-17T08:36:14+00:00",
        "remoteAddr": "92.171.26.119",
        "user": "--",
        "app": "index",
        "method": "GET",
        "url": "/",
        "message": {
            "Exception": "Error",
            "Message": "Interface 'OCP\\AppFramework\\Bootstrap\\IBootstrap' not found",
            "Code": 0,
            "Trace": [
                {
                    "file": "/var/www/html/lib/composer/composer/ClassLoader.php",
                    "line": 444,
                    "function": "include"
                },
                {
                    "file": "/var/www/html/lib/composer/composer/ClassLoader.php",
                    "line": 322,
                    "function": "Composer\\Autoload\\includeFile",
                    "args": [
                        "/var/www/html/custom_apps/w2g2/lib //AppInfo/Application.php"
                    ]
                },
                {
                    "function": "loadClass",
                    "class": "Composer\\Autoload\\ClassLoader",
                    "type": "->",
                    "args": [
                        "OCA\\w2g2\\AppInfo\\Application"
                    ]
                },
                {
                    "function": "spl_autoload_call",
                    "args": [
                        "OCA\\w2g2\\AppInfo\\Application"
                    ]
                },
                {
                    "file": "/var/www/html/lib/private/Route/Router.php",
                    "line": 401,
                    "function": "class_exists",
                    "args": [
                        "OCA\\w2g2\\AppInfo\\Application"
                    ]
                },
                {
                    "file": "/var/www/html/lib/private/Route/Router.php",
                    "line": 380,
                    "function": "setupRoutes",
                    "class": "OC\\Route\\Router",
                    "type": "->",
                    "args": [
                        {
                            "routes": [
                                {
                                    "name": "config#get_color",
                                    "url": "/color",
                                    "verb": "GET"
                                },
                                {
                                    "name": "config#directory_lock",
                                    "url": "/directory-lock",
                                    "verb": "GET"
                                },
                                {
                                    "name": "config#update",
                                    "url": "/update",
                                    "verb": "POST"
                                },
                                {
                                    "name": "lock#index",
                                    "url": "/lock",
                                    "verb": "GET"
                                },
                                {
                                    "name": "lock#store",
                                    "url": "/lock",
                                    "verb": "POST"
                                },
                                "And 1 more entries, set log level to debug to see all entries"
                            ]
                        },
                        "w2g2"
                    ]
                },
                {
                    "file": "/var/www/html/lib/private/Route/Router.php",
                    "line": 151,
                    "function": "requireRouteFile",
                    "class": "OC\\Route\\Router",
                    "type": "->",
                    "args": [
                        "/var/www/html/custom_apps/w2g2/appinfo/routes.php",
                        "w2g2"
                    ]
                },
                {
                    "file": "/var/www/html/lib/private/Route/Router.php",
                    "line": 268,
                    "function": "loadRoutes",
                    "class": "OC\\Route\\Router",
                    "type": "->",
                    "args": []
                },
                {
                    "file": "/var/www/html/lib/base.php",
                    "line": 1010,
                    "function": "match",
                    "class": "OC\\Route\\Router",
                    "type": "->",
                    "args": [
                        ""
                    ]
                },
                {
                    "file": "/var/www/html/index.php",
                    "line": 37,
                    "function": "handleRequest",
                    "class": "OC",
                    "type": ": : ",
                    "args": []
                }
            ],
            "File": "/var/www/html/custom_apps/w2g2/lib/AppInfo/Application.php",
            "Line": 34,
            "CustomMessage": "--"
        },
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv: 89.0) Gecko/20100101 Firefox/89.0",
        "version": "19.0.12.0"
    }
```
</details>

#### Browser log

NA

### Other

PS: I think you should really consider having an issue template like NextCloud ones: <https://github.com/nextcloud/server/tree/master/.github/ISSUE_TEMPLATE>

**Comment by Emi94** [comment]
@madmath03 sorry, release 3.2.6 of W2G2 was intended just for Nextcloud 21, but we failed to update that in the info.xml file of the app. I've just modified it and updated the app in the Nextcloud store. You should uninstall, version 3.2.6 of the app and install the slightly older version 3.0.3.

Note: NC instances might take a while to see the updated app in the store and still offer version 3.2.6 for older NC versions.
